[PanelSetting]
ProjectID = 52
PanelWidth =1280
PanelHeight=720
#0-4:3, 1-16:9(wide), 2-other
PanelAspectRatio=1

###########################
#       Panel output      #
###########################

#PanelDualPort: 0-single, 1-dual, 2-quad
PanelDualPort   =   0
#OddEven: panel swap port, 0-default, 1-swapped
OddEven         =   0
#Mapping: lvds TI mode, 0-normal(VESA), 1-THINE(LVDS), 2-JEIDA(LVDS), 3-PDP(LVDS)
Mapping         =   0
#ColorDepth: output format bit mode, 6-6bits, 8-8bits, 10-10bits
ColorDepth      =   8
#MirrorMode: 0-default, 1-horizontal mirror, 2-vertical mirror, 3-horizontal and vertical mirror
MirrorMode      =   0

#0-normal, 1-invert
PanelInvDCLK         =   1
PanelInvDE           =   0
PanelInvHSync        =   0
PanelInvVSync        =   0

PanelNoiseDith  = 1

###########################
#  Output tmming setting  #
###########################

PanelDCKLCurrent    =   7
PanelDECurrent      =   47
PanelODDDataCurrent =   7
PanelEvenDataCurrent=   7

PanelOnTiming0       =   20
PanelOnTiming1       =   550
PanelOnTiming2       =   75
PanelOffTiming0      =   20
PanelOffTiming1      =   250
PanelOffTiming2      =   75


PanelMaxHTotal       =   1360
PanelHTotal          =   1360
PanelMinHTotal       =   1360

PanelMaxVTotal       =   760
PanelVTotal          =   760
PanelMinVTotal       =   760


#Hz
PanelDCLK           =   62000000

PanelHsync          = 20
PanelVsync          = 2
PanelHsyncPol       = 0
PanelVsyncPol       = 0
PanelHBP            = 40
PanelVBP            = 20

#1: enable, 0: disable
SpreadSpectrumEnable = 0

#10 mean 10‰, equal to 1%
SpreadSpectrumStep = 10

#ssc frequency： 0: 31.5KHz,1: 32KHz,2: 32.5KHz,3: 33KHz
SpreadSpectrumSpan = 0


###########################
#  Panel primary gamut    #
###########################

#All values need to be multiplied by 10000
PrimaryTMax  = 3199000
PrimaryTMin  = 1228
PrimaryGamma = 22000
PrimaryRx = 6180
PrimaryRy = 3238
PrimaryGx = 3000
PrimaryGy = 6068
PrimaryBx = 1566
PrimaryBy = 381
PrimaryWx = 3127
PrimaryWy = 3290

#FreeRun
#0-Fixed Htotal, 1-Fixed Vtotal, 2-Fixed H/V total
PanelTimingWorkMode = 2

[PWMSetting]
#map to hardware PWM channel 0~7
pwm_channel     =   5
#0:high level active, 1:low level active
pwm_polarity    =   1
#hardware PWM frequence
pwm_freq        =   40000
#depends on panel, default 1
pwm_vs_lock     =   1
#minimal PWM duty, default 3
pwm_min         =   1
#maximal PWM duty
pwm_max   =   100

default_backlight   =   50
#0:manual, 1:dynamic
dynamic_backlight   =   0
